[package]
name = "todo"
version = "0.1.0"
authors = ["Felix Solcher <felix.solcher@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
xdg = "2.2.0"
regex = "1.3.9"
ansi_term = "0.12.1"
